config/routes.rb
Rails.application.routes.draw do
  get 'racers_page/index'
  resources :reservations
  resources :races
  get 'home/index'
  get 'users' ,to: 'users#index'
  root 'home#index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/race.rb
class Race < ApplicationRecord
  has_many :racers
end

app/models/racer.rb
class Racer < ApplicationRecord
  belongs_to :race
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: %i[ show edit update destroy ]

  # GET /races or /races.json
  def index
    @races = Race.all
  end

  # GET /races/1 or /races/1.json
  def show
  end

  # GET /races/new
  def new
    @race = Race.new
  end

  # GET /races/1/edit
  def edit
  end

  # POST /races or /races.json
  def create
    @race = Race.new(race_params)

    respond_to do |format|
      if @race.save
        format.html { redirect_to race_url(@race), notice: "Race was successfully created." }
        format.json { render :show, status: :created, location: @race }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /races/1 or /races/1.json
  def update
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to race_url(@race), notice: "Race was successfully updated." }
        format.json { render :show, status: :ok, location: @race }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1 or /races/1.json
  def destroy
    @race.destroy

    respond_to do |format|
      format.html { redirect_to races_url, notice: "Race was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def race_params
      params.require(:race).permit(:name,:time, :race_number, :weather, :driver)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end


  private
  def user_params
    params.require(:user).permit(:name,:email,:admin,:encrypted_password)
  end
  def create
    @user = User.new(user_params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def admin?
    current_user&.admin
  end
  def signed_in_as_admin?(i)
    if i
      'admin'
    else
      'user'
    end
  end
end

app/helpers/races_helper.rb
module RacesHelper
  def admin?
    current_user&.admin
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def admin?
    current_user&.admin
  end
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Race logger</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">

        <a class="nav-link " aria-current="page" href="#"><%= link_to 'Home', root_path, class:'navbar-brand'%></a>
        <a class="nav-link " aria-current="page" href="#"><%= link_to 'Show races', races_path, class:'navbar-brand'%></a>
        <a class="nav-link " aria-current="page" href="#"><%= link_to 'Trackdays', reservations_path, class:'navbar-brand'%></a>
        <%if admin? %>
          <a class="nav-link " aria-current="page" href="#"><%= link_to 'Add a race', new_race_path, class:'btn btn-outline-success'%></a>
        <%end %>
        <%if user_signed_in? %>

          <a class="nav-link " aria-current="page" href="#"><%= link_to 'Reserve a track day', new_reservation_path, class:'btn btn-outline-success'%></a>
          <a class='nav-link' href='#'><%= link_to "Sign out",  destroy_user_session_path,:method => :get, class:"btn btn-outline-danger" %></a>
          <a  class='nav-link' href='#'>Signed in as: <b><%= current_user.email %></b></a>
          <a  class='nav-link' href='#'>Account type: <b><%=signed_in_as_admin?(admin?) %></b></a>
        <%else %>
          <a class="nav-link " aria-current="page" href="#"><%= link_to 'Sign up', new_user_registration_path, class:'btn btn-success'%></a>
          <a class="nav-link " aria-current="page" href="#"><%= link_to 'Sign in', new_user_session_path, class:'btn btn-success'%></a>

        <%end %>



      </div>
    </div>
  </div>
</nav>

app/views/home/index.html.slim
h3 Race logger
p
  b Features:
  p -> Logging and viewing past races
  p -> Reserving track days

app/views/layouts/_alerts.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <%=notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <title>Race logger</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>

</head>
<body>

<%= render 'home/header'%>
<% if notice %>
  <%= render 'layouts/alerts'%>
<% end%>
<div class = 'container'>




  <%= yield %>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

app/views/races/_form.html.slim
= form_with(model: @race) do |form|
  - if @race.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@race.errors.count, "error")} prohibited this race from being saved:"
      ul
        - @race.errors.each do |error|
          li = error.full_message

  div
    div
      = form.text_field :name ,class:'form-control',placeholder:"Name of the race"
      = form.text_field :race_number ,class:'form-control',placeholder:"Race number"
      = form.text_field :time ,class:'form-control',placeholder:"Fastest race finish time"
      = form.text_field :driver ,class:'form-control',placeholder:"Fastest driver"
      = form.text_field :weather ,class:'form-control',placeholder:"Dry or wet"
      = form.submit class:"btn btn-success"

app/views/races/_race.html.slim
div id="#{dom_id race}"
  p
    b Name
    =race.name
  p
    b Race Number:
    =race.race_number
  p
    b Race time:
    =race.time
  p
    b Winner
    =race.driver
  p
    b Weather
    =race.weather

app/views/races/edit.html.slim
h1 Editing race

== render "form", race: @race

br

div

  =< link_to "Back to races", races_path,class:"btn btn-outline-success"

app/views/races/index.html.slim
p style="color: green" = notice

h1 Races
table class="table table-bordered"
  thead
    tr
      th Name
      th Race number
      th Race time
      th Winner
      th Weather
      th Action
  tbody


  - @races.each do |race|
    tr
      td =race.name
      td =race.race_number
      td =race.time.to_s + " minutes"
      td =race.driver
      td
        -if race.weather == 'dry'
          b
            div style="color:black"
              =race.weather
        -else
          b
            div style="color:blue"
              =race.weather
      td
        -if admin?
          =link_to "Edit", race
        -else
          b = 'Sign into and admin account to edit a race'

app/views/races/new.html.slim
h1 New race

== render "form", race: @race

br

div
  = link_to "Back to races", races_path

app/views/races/show.html.slim
p style="color: green" = notice

== render @race

div

  => link_to "Edit this race", edit_race_path(@race), class:"btn btn-outline-warning"
  '|
  =< link_to "Back to races", races_path, class:"btn btn-outline-info"

  = button_to "Destroy this race", @race,class:"btn btn-danger", method: :delete

app/views/users/index.html.slim
h1 Motopark ostrava